sudo required

diff --git a/07-20 b/07-20
--- a/07-20
+++ b/07-20
@@ -79,9 +79,17 @@ else
 
     echo "🚀  Installing";
 
-    sudo mkdir -p $INSTALL_LOC;
-    sudo rm -rf "$INSTALL_LOC/$TOOLCHAIN";
-    sudo mv $TOOLCHAIN $INSTALL_LOC;
+    mkdir -p $INSTALL_LOC;
+    mv $TOOLCHAIN $INSTALL_LOC;
+    if [ $? -eq 0 ]; 
+    then
+        # ok
+    else
+        echo "🔒  Sudo required";
+        sudo mkdir -p $INSTALL_LOC;
+        sudo rm -rf -p $TOOLCHAIN $INSTALL_LOC;
+        sudo mv $TOOLCHAIN $INSTALL_LOC;
+    fi
 fi
 
 swiftenv global $NAME
